version: '3.8'

services:
  app:
    container_name: ms-product-ml-nestjs
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run start:dev
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
